Student/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Student.Models
{
    public class Student
    {
        [Display(Name = "Id")]
        public int ID { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Mobile is required.")]
        public string Mobile { get; set; }
    }
}

Student/Models/StudentBL.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace Student.Models
{
    public class StudentBL
    {
        private string connectionString = ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;

        public IPagedList<Student> GetAllStudent(int page, int pageSize)
        {
            List<Student> emp = new List<Student>();
            using(SqlConnection con = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("ListStudent", con);
                cmd.CommandType = CommandType.StoredProcedure;
                con.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    Student std = new Student();
                    std.ID = Convert.ToInt32(rdr["ID"]);
                    std.Name = rdr["Name"].ToString();
                    std.Email = rdr["Email"].ToString();
                    std.Mobile = rdr["Mobile"].ToString();

                    emp.Add(std);

                }
                con.Close();

            }
            return emp.ToPagedList(page, pageSize);
        }
        private SqlConnection con;

        private void connection()
        {
            string constr = ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;
            con = new SqlConnection(constr);

        }
        public List<Student> GetById()
        {
            List<Student> emp = new List<Student>();
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("ListStudent", con);
                cmd.CommandType = CommandType.StoredProcedure;
                con.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    Student std = new Student();
                    std.ID = Convert.ToInt32(rdr["ID"]);
                    std.Name = rdr["Name"].ToString();
                    std.Email = rdr["Email"].ToString();
                    std.Mobile = rdr["Mobile"].ToString();

                    emp.Add(std);
                }
                con.Close();
            }
            return emp;
        }
        public bool AddStudent(Student obj)
        {
            connection();
            SqlCommand com = new SqlCommand("AddStudent", con);
            com.CommandType = CommandType.StoredProcedure;
            com.Parameters.AddWithValue("@Name", obj.Name);
            com.Parameters.AddWithValue("@Email", obj.Email);
            com.Parameters.AddWithValue("@Mobile", obj.Mobile);

            con.Open();
            int i = com.ExecuteNonQuery();
            con.Close();
            if (i >= 1)
            {

                return true;

            }
            else
            {

                return false;
            }

        }
        public bool UpdateStudent(Student obj)
        {

            connection();
            SqlCommand com = new SqlCommand("UpdateStudent", con);

            com.CommandType = CommandType.StoredProcedure;
            com.Parameters.AddWithValue("@ID", obj.ID);
            com.Parameters.AddWithValue("@Name", obj.Name); 
            com.Parameters.AddWithValue("@Email", obj.Email);
            com.Parameters.AddWithValue("@Mobile", obj.Mobile);
            con.Open();
            int i = com.ExecuteNonQuery();
            con.Close();
            if (i >0)
            {

                return true;
            }
            else
            {
                return false;
            }
        }
        public bool DeleteStudent(int Id)
        {

            connection();
            SqlCommand com = new SqlCommand("DeleteStudent", con);

            com.CommandType = CommandType.StoredProcedure;
            com.Parameters.AddWithValue("@ID", Id);

            con.Open();
            int i = com.ExecuteNonQuery();
            con.Close();
            if (i >= 1)
            {
                return true;
            }
            else
            {

                return false;
            }
        }
    }
 }

Student/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Student.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Student/Controllers/StudentController.cs
using Student.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Student.Controllers
{
    public class StudentController : Controller
    {
        private StudentBL obj = new StudentBL();
         
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            var result = obj.GetAllStudent(page, pageSize);
            
            return View(result);
        }

        [HttpGet]
        public ActionResult AddStudent()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddStudent(Student.Models.Student std)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    StudentBL student = new StudentBL();
                    bool effacetedId = student.AddStudent(std);
                    if (effacetedId)
                    {
                        TempData["SUCCESS"] = "Student  added successfully";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["ERROR"] = "Student  added FAILD";
                        return RedirectToAction("Index");
                    }
                }
            }
            catch
            {
                return View();
            }
            return View();
        }
        public ActionResult EditStudent(int id)
        {
            StudentBL std = new StudentBL();

            return View(std.GetById().FirstOrDefault(x => x.ID == id));
        }

        [HttpPost]
        public ActionResult EditStudent(Student.Models.Student obj)
        {
            try
            {
                StudentBL std = new StudentBL();

               bool EffectedId =  std.UpdateStudent(obj);
                if (EffectedId) {
                    TempData["SUCCESS"] = "Update Record successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ERROR"] = "Update Record Faild !";
                    return RedirectToAction("AddStudent");
                }
            }
            catch(Exception ex)
            {
                throw new Exception();
            }
        }
        public ActionResult DeleteStd(int Id)
        {
            try
            {
                StudentBL std = new StudentBL();
                if (std.DeleteStudent(Id))
                {
                    TempData["SUCCESS"] = "Student details deleted successfully";
                    return RedirectToAction("index");
                }
                else
                {
                    TempData["ERROR"] = "Faild TO Delete Data  !";
                    return RedirectToAction("index");
                }
            }
            catch(Exception ex)
            {
                throw new Exception();
            }
        }
    }
}

Student/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Student/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Student/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Student/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Student/Views/Student/AddStudent.cshtml
@model Student.Models.Student
@{
    ViewBag.Title = "AddStudent";
}
@using (Html.BeginForm("AddStudent", "Student", FormMethod.Post))
{
    <br />
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-6">
                    <label>Name<span class="text-danger">*</span></label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    <span class="messages"></span>
                    @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6">
                    <label>Email</label>
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-12">
                <div class="col-md-6">
                    <label>Mobile</label>
                    @Html.TextBoxFor(x => x.Mobile, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 col-md-6">
                    <br />
                    <input type="submit" value="Save" class="btn btn-success" />
                    <a href="@Url.Action("index","Student")" class="btn btn-danger">CANCEL</a>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 col-md-6" style="color:green">
                    @TempData["ERROR"]

                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Student/Views/Student/EditStudent.cshtml
@model Student.Models.Student
@{
    ViewBag.Title = "EditStudent";
}
@using (Html.BeginForm("EditStudent", "Student", FormMethod.Post))
{
    <br />
    <div class="container">
        <div>@TempData["ERROR"]</div>
        <div class="row">
            <div class="col-md-12">
                <div>
                    @Html.HiddenFor(x => x.ID)
                </div>
                <div class="col-md-6">
                    <label>Name<span class="text-danger">*</span></label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    <span class="messages"></span>
                    @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6">
                    <label>Email</label>
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-12">
                <div class="col-md-6">
                    <label>Mobile</label>
                    @Html.TextBoxFor(x => x.Mobile, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 col-md-6">
                    <br />
                    <input type="submit" value="Update" class="btn btn-success" />
                    <a href='@Url.Action("index","Student")' class="btn btn-danger">CANCEL</a>
                </div>
            </div>
        </div>
    </div>
}

Student/Views/Student/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<Student.Models.Student>

<br />
@using (Html.BeginForm("index", "Student", FormMethod.Get))
{
    <p>
        <b>Search By:</b>
        @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}
<div class="row">
    <div class="alert-success">@TempData["SUCCESS"]</div>
    <div class="col-md-12 text-right">
        <a href="@Url.Action("AddStudent","Student")" class="btn btn-danger">Add New</a>
    </div>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>S.NO</th>
            <th>Name</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{ int index = 0;}
        @foreach (var item in Model)
        {
            index++;
            <tr>
                <td>@index</td>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>@item.Mobile</td>
                <td>
                    @Html.ActionLink("Edit", "EditStudent", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "DeleteStd", new { Id = item.ID }, new { onclick = "return confirm('Are sure wants to delete?');" })
                </td>
            </tr>

        }
    </tbody>

</table>
    <div class="pagedList">
        @Html.PagedListPager(Model, page => Url.Action("index", "Student", new { page }),
    PagedListRenderOptions.PageNumbersOnly/*MinimalWithPageCountText*/)
    </div>

@*<div class="pagination" style="margin-left: 400px">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        of @Model.PageCount   @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>*@